### ISSUE TITLE
ons-pull-hook: content flicker bug still remains on iOS

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#1990]
__Environment__ 

```
[Core]
    onsenui 2.2.6

[Framework]
    none

[Framework binding]
    none

[Additional libraries]
    none

[Platform]
    Mobile - iOS 10.1.1

[Browser]
    Mobile - iOS UIWebView
```

__Encountered problem__
The same to #485 .

__How to reproduce__
1. Make a `ons-page` which can be scrolled
2. Put a `ons-pull-hook`
3. Pull the page slowly

This issue happens only with iOS's webview.

I made a sample Monaca project to reproduce the issue.
[ons-pull-hook-flicker-bug.zip](https://github.com/OnsenUI/OnsenUI/files/971192/ons-pull-hook-flicker-bug.zip)
Please import this project and run in Monaca debugger app.

**Comment by asial-matagawa** [comment]
@puku0x 
Sorry for the delay.
Thank you for reporting!

We will investigate this problem as soon as possible, but we've been working on [the pull requests](https://github.com/OnsenUI/OnsenUI/pulls). Please be patient for a while...

**Comment by puku0x** [comment]
Is there any progress for this issue ?
As you can see, the flicker bug makes UX worse 😢 

<img src="https://user-images.githubusercontent.com/2607019/30409569-e1b25210-9940-11e7-9ded-bf98e4d2ddb6.gif" width="240px">

**Comment by frandiox** [comment]
@puku0x Thanks for reporting and providing code! This bug was a hard one :sweat_smile:
It will be out in the next release. This also fixes another glitch for Android :+1:

**Comment by puku0x** [comment]
@frandiox Thank you !
I'm looking forward to the next release.

**Comment by Hirbod** [comment]
@frandiox is this fixed in th newes 2.6.0 ?

**Comment by asial-matagawa** [comment]
@Hirbod 
Yes, it has been fixed.
@puku0x posted a screenshot of Onsen UI 2.6.0 on Twitter: https://twitter.com/puku0x/status/910109182275096578

**Comment by Hirbod** [comment]
@frandiox @asial-matagawa you can't believe how many hours I tried to debug this problem. I guess like 2-3 days and I tried so many hacks. Just installed 2.6.0 and it is just PERFECT. THANK YOU GUYS. Gonna drink a glass of gintonic now!

**Comment by frandiox** [comment]
@Hirbod I can believe it, it was hard to find a solution :sweat_smile: Enjoy the gin :party_parrot:

**Comment by Hirbod** [comment]
@frandiox after intensive testing I am still pretty happy, but there are some issues remaining.
It will jitter when reaching the bottom. 

And there was a problem when having a long list and "reaccelerate" scroll while still in inertial/momentum. This was annoying. I googled a simple method to detect if momentum has stopped or not and added a disabled attribute to the hook while "still in momentum" and removed the disabled attribute when momentum has finished.

This fixed every jitter problem which was left.
